name: flutter_store_shoe
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  velocity_x: ^4.1.1
  badges: ^3.1.2
  get: ^4.6.6
  dio: ^5.3.3
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.14
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.1.0
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.2.2
  awesome_dialog: ^3.1.0
  loading_indicator: ^3.1.1
  cached_network_image: ^3.3.0
  provider: ^6.0.5
  mvc_pattern: ^8.12.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.0+2
  extended_image: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/design/
    - assets/design/images/
    - assets/components/

  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
